---
language: node_js
node_js:
  - "6"

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - npm test

after_success:
  - ember build -prod
  - firebase deploy --token "${FIREBASE_TOKEN}"
