// Source:
// http://www.dmv.state.va.us/webdoc/pdf/vsa-6color.pdf
export default {
  'BGE': 'beige',
  'BLK': 'black',
  'BLU': 'blue',
  'BRO': 'brown',
  'BRZ': 'bronze',
  'CAM': 'camouflage',
  'COM': 'chrome',
  'CPR': 'copper',
  'CRM': 'cream',
  'DBL': 'dark blue',
  'DGR': 'dark green',
  'GLD': 'gold',
  'GRN': 'green',
  'GRY': 'gray',
  'LBL': 'light blue',
  'LGR': 'light green',
  'MAR': 'maroon',
  'ONG': 'orange',
  'PLE': 'purple',
  'PNK': 'pink',
  'RED': 'red',
  'SIL': 'silver',
  'TAN': 'tan',
  'TEA': 'teal',
  'TPE': 'taupe',
  'TRQ': 'turquoise',
  'WHI': 'white',
  'YEL': 'yellow',
};
